# 指令前缀 若和别的游戏冲突，更换其他前缀即可
rulePrefix:
- "!"
- "！"
- "#?异环"

# 角色图片
imgMaxSize: 10 #上传图片大小限制 MB
imgPath:
#角色图片库的路径 从Bot根目录开始，如 'plugins/NTE-image/' ，路径下须是以角色命名的文件夹
- plugins/NTE-image
# todo
characterImgPath: [] #立绘图 无背景图片 
# todo
heroGuidePath: [] #角色攻略图
imgUpAuth: all # 图片上传权限 "master"|"admin"|"owner"|"all"
imgDelAuth: all # 图片删除权限 "master"|"admin"|"owner"|"all"


# 签到
sign: true # 开启签到
signWithdrawal: 90 # 签到撤回
signInclude: [] # 签到包含群聊
signExclude: [] # 签到排除群聊